FinalProj/Controllers/ClientSideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IS445.Controllers
{
    public class ClientSideController : Controller
    {
        //
        // GET: /ClientSideDemo/


        public ActionResult ClientSide()
        {
            return View();
        }

        public ActionResult FormatStringBackwards(string inputString)
        {

            if (string.IsNullOrEmpty(inputString))
            {
                return Content("invalid input, please try again");
            }
            else
            {
                string formatted = formatString(inputString);
                return View((object)formatted);
            }
        }

        private string formatString(string inputString)
        {
            // imiplement formatting here
            string finalstring = "";

            string[] words = inputString.Split(' ');
            foreach (string word in words)
            {
                finalstring = String.Concat(word, " ", finalstring);
            }

            return "formated number is: " + finalstring;
        }

    }
}

FinalProj/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IS445.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WebForm()
        {
            return View();
        }

        public ActionResult Bio()
        {
            return View();
        }
        public ActionResult AbsoluteLayout()
        {
            return View();
        }
        public ActionResult StaticLayout()
        {
            return View();
        }
        public ActionResult FloatLayout()
        {
            return View();
        }
        public ActionResult ClientSideDemo()
        {
            return View();
        }
        public ActionResult ServerSideDemo()
        {
            return View();
        }

        public ActionResult FormatPhoneNumber(string inputNumber)
        {

            if (string.IsNullOrEmpty(inputNumber))
            {
                return Content("invalid input, please try again");
            }
            else
            {
                string formatted = formatNumber(inputNumber);
                return View((object)formatted);
            }
        }

        // please implement your phone number formatting logic here
        private string formatNumber(string inputNumber)
        {
            // imiplement formatting here

            string finalstring = inputNumber;

            inputNumber = String.Concat("(", finalstring.Substring(0, 3), ") ", finalstring.Substring(3, 3), "-", finalstring.Substring(6, 4));

            return "formated number is: " + inputNumber;
        }
    }
}

FinalProj/Views/ClientSide/FormatStringBackwards.cshtml
@model string

@{
    ViewBag.Title = "FormatStringBackwards";
}

<h2>FormatStringBackwards</h2>

<h3>your formatted String backwards is @Model </h3>

FinalProj/Views/Home/AbsoluteLayout.cshtml
@{
    ViewBag.Title = "AbsoluteLayout";
}

  <link href="~/Content/absolute1.css" rel="stylesheet" />

  <article> &lt;My Article&gt;
    <section>&lt;Section One&gt;</section>
    <section>&lt;Section Two&gt;</section>
  </article>
  <aside>&lt;Aside&gt;</aside>
  <footer>&lt;Footer&gt;</footer>

FinalProj/Views/Home/Bio.cshtml
@model string

@{
    ViewBag.Title = "Bio";
}


@using (Html.BeginForm())
{
    <h2>About myself</h2>
    <img class="revypic" src="~/Content/JenRevy01.jpg"/>
    <h3 class="alignleft">Education</h3>
    <ul>
        <li>2010, BS Business Administration: Information Systems, Cal Poly San Luis Obispo</li>
        <li>2013, MBA Information Systems, CSULB</li>
    </ul>
    <h3 class="alignleft">Working experience</h3>
    <ul>
        <li>Project and Cost Control Analyst, Northrop Grumman, 3.5 years</li>
        <li>Data Center Technician, Cal Poly San Luis Obispo, 1 year</li>
    </ul>
    <h3 class="alignleft">Expectation for this course</h3>
    <p>
    I currently accepted a job offer for a web developer position in Australia with my company.  
    I am really looking to working with Javascript as SQL and javascript are really the main things I will be 
    working with.
    </p>
    <br />
}

FinalProj/Views/Home/ClientSideDemo.cshtml
@{
    ViewBag.Title = "ClientSideDemo";
}

@using (Html.BeginForm("FormatStringBackwards", "ClientSide"))
{
  <label for="inputNumber">Please Input a String</label>
  <input type="text" name="inputString" id="inputString" value=""/>
  <input type="submit" name="submit" value="submit" />
}

FinalProj/Views/Home/FloatLayout.cshtml
@{
    ViewBag.Title = "FloatLayout";
}

  <link href="~/Content/float.css" rel="stylesheet" />

  <article> &lt;My Article&gt;
    <section>&lt;Section One&gt;</section>
    <section>&lt;Section Two&gt;</section>
  </article>
  <aside>&lt;Aside&gt;</aside>
  <footer>&lt;Footer&gt;</footer>

FinalProj/Views/Home/FormatPhoneNumber.cshtml
@model string

@{
    ViewBag.Title = "FormatPhoneNumber";
}

<h3>Your formatted phone number is @Model </h3>

FinalProj/Views/Home/Index.cshtml
@model string

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm())
{
    <h3>Welcome to my home page</h3>
    <body>This website gives many examples of the benefits of ASP.NET.  There are many_
        other things that have been shown on this website.  There are examples of_
        Javascript, CSS, HTML, and server and client side calculations.  These_
        skills are extremely useful when creating applications on websites.  I_
        believe I would be a great asset to any team, please take a look around_
        this sample website of my work and the different things that I was able_
        to accomplish.
    </body>

    <br />
    <br />
}

FinalProj/Views/Home/ServerSideDemo.cshtml
@{
    ViewBag.Title = "ServerSideDemo";
}

@using (Html.BeginForm("FormatPhoneNumber", "Home"))
{
  <label for="inputNumber">Please input a phone number: </label>
  <input type="text" name="inputNumber" id="inputNumber" value=""/>
  <input type="submit" name="submit" value="submit" />
}

FinalProj/Views/Home/StaticLayout.cshtml
@{
    ViewBag.Title = "StaticLayout";
}

 <link href="~/Content/static.css" rel="stylesheet" />

  <article> &lt;My Article&gt;
    <section>&lt;Section One&gt;</section>
    <section>&lt;Section Two&gt;</section>
  </article>
  <aside>&lt;Aside&gt;</aside>
  <footer>&lt;Footer&gt;</footer>

FinalProj/Views/Home/WebForm.cshtml
@model string
@{
    ViewBag.Title = "WebForm";
}

@using (Html.BeginForm())
{

    
    <h2>Welcome to my Web Form</h2>
    <h3>A demo form for hotel room reservation</h3>

    <form action="#" method="get">
        <fieldset>
            <legend>Customer Information</legend>
            <label>
                Full name: 
                <input type="text" name="name" id="Field1" size="30" maxlength="100" placeholder="Firstname Lastname" />
            </label>
            <br />
            <label>
                Email address:
                <input type="email" id="Field2" name="email" size="30" maxlength="100" />
            </label>
            <br />
            <label>
                Phone:
                <input type="text" id="Field3" name="phonenumber" size="30" maxlength="10" />
            </label>
        </fieldset>
        <fieldset>
            <legend>
                Room Information
            </legend>
            <label>
                Arrival date:
                <input type="date" id="Field4" name="Arrivaldate"/>
            </label>
            <br />
            <label>
                Arrival time:
                <input type="time" id="Field5" name="Arrivaltime"/>
            </label>
            <br />
            <label>
                Select a room type:
                <select name="roomtype" id="Field6">
                    <option value="Luxury">Luxury</option>
                    <option value="Standard">Standard</option>
                    <option value="Economic">Economic</option>
                </select>
            </label>
            <br />
            <label>
                Number of nights (valid number is from 1 to 30):
                <input type="number" max="30" name="Nights" id="Field7" value="1" />
            </label>
            <br />
            <label>
                Number of guests (the maximum guests is ):
                <input type="number" max="3" name="guests" id="Field8" value="0" />
            </label>
        </fieldset>
        <fieldset>
            <legend>
                Other Information
            </legend>
            <label>
                Promo code:
                <input type="text" name="Promocode" id="Field9" />
            </label>
            <br />
            <label>
                Special Note:
            </label>
            <textarea rows="5" cols="40" id="Field10" name="Notes"></textarea>
        </fieldset>
        <input type="button" value="Clear form" onclick="window.location.reload()"/>
        <input type="submit" value="Request Reservation" />
    </form>
}

FinalProj/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cox, Chase Final Project</title>
    <link href="@Url.Content("~/Content/StyleSheetMain.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
    <h1>Cox, Chase Final Project</h1>

    <div>
        <a href="~/Home/index" id="menu">Home
	    </a>
	    <a href="#" id="menu">Form/Layout Demos
            <span>
                <b onclick="location.href='/Home/WebForm'">Web Form</b>
                <b onclick="location.href='/Home/AbsoluteLayout'">Absolute Layout</b>
                <b onclick="location.href='/Home/StaticLayout'">Static Layout</b>
                <b onclick="location.href='/Home/FloatLayout'">Float Layout</b>
            </span>
        </a>
        <a href="~/Home/ClientSideDemo" id="menu">ClientSide Demo
        </a>
        <a href="~/Home/ServerSideDemo" id="menu">ServerSide Demo
        </a>
        <a href="~/Home/Bio" id="menu">About Myself
        </a>
    </div>
    </header>
    <div>
        @RenderBody()
    </div>
@*    <footer>
        <address>Chase Cox&#169 Contact Information</address>
        <address><a href="mailto:chase.cox@csulb.edu">Email: chase.cox@csulb.edu</a></address>
        <address><i>Phone:(562)985-4554</i></address>
    </footer>*@
</body>
</html>